# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1927-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.cache/wt [current_project]
set_property parent.project_path /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.cache/ip [current_project]
set_property ip_cache_permissions disable [current_project]
add_files /home/rnt/workspace/XDMA_Accelerator_edditing/Bram_init/1.coe
add_files /home/rnt/workspace/XDMA_Accelerator_edditing/Bram_init/matrix_data.coe
read_verilog -library xil_defaultlib -sv {
  /home/rnt/workspace/XDMA_Accelerator/RTL/Compute_Muticast/Gather_C.sv
  /home/rnt/workspace/XDMA_Accelerator/RTL/Compute_Muticast/Matrix_Multiply.sv
  /home/rnt/workspace/XDMA_Accelerator/RTL/Compute_Muticast/PE.sv
  /home/rnt/workspace/XDMA_Accelerator/RTL/Compute_Muticast/PE_array.sv
  /home/rnt/workspace/XDMA_Accelerator/RTL/Compute_Muticast/Scatter_A.sv
  /home/rnt/workspace/XDMA_Accelerator/RTL/Compute_Muticast/Usr_Logic.sv
  /home/rnt/workspace/XDMA_Accelerator/RTL/Compute_Muticast/compute_control.sv
  /home/rnt/workspace/XDMA_Accelerator/RTL/Compute_Muticast/scatter_B.sv
  /home/rnt/workspace/XDMA_Accelerator/RTL/Compute_Muticast/xilinx_dma_pcie_ep.sv
}
read_verilog -library xil_defaultlib {
  /home/rnt/workspace/XDMA_Accelerator/RTL/Compute_Muticast/Usr_control.v
  /home/rnt/workspace/XDMA_Accelerator/RTL/Compute_Muticast/xdma_app.v
}
read_ip -quiet /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/xdma_0/xdma_0.xci
set_property used_in_implementation false [get_files -all /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/xdma_0/xdma_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/xdma_0/source/xdma_0_pcie3_7vx_ip.xdc]
set_property used_in_implementation false [get_files -all /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/xdma_0/synth/xdma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/xdma_0/ip_0/source/xdma_0_pcie3_ip-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/xdma_0/ip_0/synth/xdma_0_pcie3_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/xdma_0/ip_1/xdma_v4_1_2_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/xdma_0/ip_2/xdma_v4_1_2_blk_mem_64_noreg_be_ooc.xdc]

read_ip -quiet /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property used_in_implementation false [get_files -all /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0_ooc.xdc]

read_ip -quiet /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all /home/rnt/workspace/XDMA_Accelerator/xdma_0_ex.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/rnt/workspace/XDMA_Accelerator/imports/xilinx_pcie_xdma_ref_board.xdc
set_property used_in_implementation false [get_files /home/rnt/workspace/XDMA_Accelerator/imports/xilinx_pcie_xdma_ref_board.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top xilinx_dma_pcie_ep -part xc7vx690tffg1927-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xilinx_dma_pcie_ep.dcp
create_report "synth_3_synth_report_utilization_0" "report_utilization -file xilinx_dma_pcie_ep_utilization_synth.rpt -pb xilinx_dma_pcie_ep_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
