set_property SRC_FILE_INFO {cfile:/home/guocheng/soft/eda/xilinx/vivado/kc705/pcie_intrp_ex/xdma_0_ex/imports/xilinx_pcie_xdma_ref_board.xdc rfile:../../../imports/xilinx_pcie_xdma_ref_board.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G25 [get_ports sys_rst_n]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X0Y1 [get_cells refclk_ibuf]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8 [get_ports led_0]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports led_1]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC9 [get_ports led_2]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB9 [get_ports led_3]
